x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  bridge:
    image: husarion/ros:galactic-ros1-bridge
    <<: *net-config
    command: ros2 run ros1_bridge dynamic_bridge --bridge-all-1to2-topics

  openmanipulatorx:
    image: openmanipulatorx-gravity-compensation:melodic
    <<: *net-config
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./config/gravity_compensation.launch:/gravity_compensation.launch
    devices:
      - /dev/ttyMANIPULATOR:/dev/ttyUSB0
    # TODO: fix
    command: bash -c "sudo chmod 777 /dev/ttyUSB0 && \
      roslaunch /gravity_compensation.launch usb_port:=/dev/ttyUSB0 baud_rate:=1000000"

  manipulator_cmd_vel_controller:
    image: openmanipulatorx-gravity-compensation:melodic
    <<: *net-config
    volumes:
      - ./config/manipulator_cmd_vel_controller.py:/home/maciej/catkin_ws/src/open_manipulator_controls/open_manipulator_controllers/src/manipulator_cmd_vel_controller.py
    command: rosrun open_manipulator_controllers manipulator_cmd_vel_controller.py

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    <<: *net-config
    command: MicroXRCEAgent udp4 --port 8888
  
  rosbot-xl:
    image: husarion/rosbot-xl:humble
    <<: *net-config
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=False