x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  # bridge:
  #   image: husarion/ros:galactic-ros1-bridge
  #   restart: unless-stopped
  #   environment:
  #     - ROS_IP=127.0.0.1
  #     - ROS_MASTER_URI=http://127.0.0.1:11311
  #     - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
  #     - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
  #   command: >
  #     ros2 run ros1_bridge dynamic_bridge --bridge-all-topics 
  #   network_mode: host
  #   ipc: host

  ros-master:
    image: ros:melodic-ros-core
    <<: *net-config
    command: stdbuf -o L roscore

  openmanipulatorx:
    image: openmanipulatorx-gravity-compensation:melodic
    <<: *net-config
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./config/gravity_compensation.launch:/gravity_compensation.launch
    devices:
      - /dev/ttyMANIPULATOR:/dev/manipulator
    # command: roslaunch open_manipulator_controllers gravity_compensation_controller.launch usb_port:=/dev/ttyUSB0
    command: roslaunch --wait /gravity_compensation.launch usb_port:=/dev/manipulator baud_rate:=1000000

  manipulator_cmd_vel_controller:
    image: openmanipulatorx-gravity-compensation:melodic
    <<: *net-config
    volumes:
      - ./config/manipulator_cmd_vel_controller.py:/home/maciej/catkin_ws/src/open_manipulator_controls/open_manipulator_controllers/src/manipulator_cmd_vel_controller.py
    command: rosrun open_manipulator_controllers manipulator_cmd_vel_controller.py
